### ISSUE TITLE
Instructions on how to use?

### ISSUE THREAD

**Issue by riahc3** [Briiqn/BriiqnGen#1]
Hello

Could you leave some Instructions on how to use?

**Comment by Briiqn** [comment]
Install requirements.txt, install openai whisper with their guide & the run main.py

**Comment by Briiqn** [comment]
Install requirements.txt, install openai whisper with their guide & then run main.py

**Comment by riahc3** [comment]
But their thing seems to be like a TTS or something....What does that have to do with generating Outlook accounts?

**Comment by Briiqn** [comment]
Its not tts its speech recognition (if you looked at the project this should alr been evident) & there was a captcha that existed that only required you to type in what you hear
