### ISSUE TITLE
Multiple Issues

### ISSUE THREAD

**Issue by namanbhardwaj46** [Briiqn/BriiqnGen#2]
Which version of whisper should be used, it's not mentioned in requirements file, as latest module leads to different error.

![Screenshot 2023-06-02 010636](https://github.com/Briiqn/BriiqnGen/assets/68163575/04f81d9f-7cd8-487f-94d3-84a9a63cdddf)

**Comment by Briiqn** [comment]
Hi, the version shouldnt  be an issue, instead the path formatting seems to be the issue. This is due to me writing thia on linux where '/' defines a path/folder but windows does not. Furthermore i do not have plans in the foreseeable future to update this as it is patched.
